test:
  access_key_id: 'AKIAJ7DKVQDPY55BZSHQ'
  secret_access_key: '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'

dev:
  access_key_id: 'AKIAJ7DKVQDPY55BZSHQ'
  secret_access_key: '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'

staging:
  access_key_id: 'AKIAJ7DKVQDPY55BZSHQ'
  secret_access_key: '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'
