development:
  adapter: mysql
  database: tapjoy_db
  host: localhost
  username: root
  password:
  reconnect: true

test:
  adapter: mysql
  database: tapjoy_db_test
  host: localhost
  username: root
  password:
  reconnect: true

staging:
  adapter: mysql
  database: tapjoy_db_staging
  host: localhost
  username: root
  password:
  reconnect: true

production:
  adapter: mysql
  database: tapjoy_db
  host: tapjoy-db-rds.cck8zbm50hdd.us-east-1.rds.amazonaws.com
  username: tapjoy
  password: andoverbusiness1
  reconnect: true

production_slave_for_tapjoy_db:
  adapter: mysql
  database: tapjoy_db
  host: tapjoy-db-rds-replica1.cck8zbm50hdd.us-east-1.rds.amazonaws.com
  username: tapjoy
  password: andoverbusiness1
  reconnect: true

production_slave:
  adapter: mysql
  database: tapjoy_db
  host: replica.tapjoy.com
  username: tapjoy
  password: xatrugAxu6
  reconnect: true

sqlite:
  adapter: sqlite3
  database: db/webserver.sqlite
