production:
  app_id: '276090845745399'
  secret: '38698ac9e364133fc42e43fad3208277'
  api_key: '276090845745399'
  oauth2: true

development:
  app_id: '281461335227331'
  secret: 'c2338efd83e1abe81f3ef798837a6a91'
  api_key: '281461335227331'
  oauth2: true

test:
  app_id: '281461335227331'
  secret: 'c2338efd83e1abe81f3ef798837a6a91'
  api_key: '281461335227331'
  oauth2: true

staging:
  app_id: '281461335227331'
  secret: 'c2338efd83e1abe81f3ef798837a6a91'
  api_key: '281461335227331'
  oauth2: true