defaults: &defaults
  js_version: '1.54'
  js_files: [
    'tjg.jquery-1.6.2.min',
    'init',
    'jqtouch',
    'utils',
    'i18n',
    'ui',
    'social',
    'tapjoygames'
  ]
  js_compile_out_file: 'tjgames.min'

test:
  <<: *defaults

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
